name: PR File List

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List PR Files
        uses: ./.github/actions/list-pr-files
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}