name: PR File List

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const files = ${{ steps.changed-files.outputs.all_changed_files }}
            const fileList = files.join('\n');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `This PR includes the following files:\n\n${fileList}`
            })